### PR TITLE
1: Initial version of graph-build-times GitHub action

### LINKED ISSUE #1: Create the GitHub action

### PR DESCRIPTION
**Pull request by JacobDomagala**
Fixes #1

### CODE REVIEW

**Comment by JacobDomagala** [comment]
Action used for https://github.com/DARMA-tasking/vt/pull/1269. The output graph can be seen on https://github.com/DARMA-tasking/vt/wiki/Build-Requirements

**Comment by cz4rs** [comment]
something from nice-to-have category: we could use some dates (for reference) apart from run number on the horizontal axis

**Comment by JacobDomagala** [comment]
> something from nice-to-have category: we could use some dates (for reference) apart from run number on the horizontal axis

@cz4rs  I will see whether it's possible to add dates in a way that it doesn't get messy

**Review by cz4rs — APPROVED** [review]
looks good overall :+1:

**Comment by JacobDomagala** [comment]
Updated with the dates

**Review by jstrzebonski — APPROVED** [review]

**Pull request merged**
