### PR TITLE
9: Add performance tests

### LINKED ISSUE #9: Add performance tests to the action

### PR DESCRIPTION
**Pull request by JacobDomagala**
Fixes #9

## Changes:
- Run performance tests with `--vt_perf_gen_file` runtime flag
- Run heaptrack on `jacobi2d_vt` and generate 3 flamegraphs:
1. Number of allocations
2. Size of allocations
3. Size of leaked memory
- Parse the files generated by performance tests and generate:
1. History of runs for that test
2. Separate graph for each timer inside the test
3. Memory usage for that test
- Generate Markdown wiki page: https://github.com/DARMA-tasking/vt/wiki/Perf-Tests

### CODE REVIEW

**Comment by JacobDomagala** [comment]
[](https://github.com/DARMA-tasking/vt/wiki/perf_tests/test.svg)

**Comment by cz4rs** [comment]
I have run `pylint` on this branch and there are some warnings that should probably be fixed. I didn't filter anything, but we can ignore line length and some minor ones (on that note, I'm not sure what's the latest and greatest in Python linting, maybe some other tool would be better).
Anyways, seeing as the amount of code here grows, we could enable at least simple linting for this repo (see https://github.com/marketplace/actions/python-code-quality-and-lint for example).

<details>
  <summary>pylint output</summary>

```
 cz4rs  ~  nga  pylint build-stats/
************* Module generate_wiki_pages
build-stats/generate_wiki_pages.py:150:0: C0301: Line too long (103/100) (line-too-long)
build-stats/generate_wiki_pages.py:237:0: C0301: Line too long (101/100) (line-too-long)
build-stats/generate_wiki_pages.py:273:0: C0301: Line too long (101/100) (line-too-long)
build-stats/generate_wiki_pages.py:285:0: C0301: Line too long (112/100) (line-too-long)
build-stats/generate_wiki_pages.py:286:0: C0301: Line too long (158/100) (line-too-long)
build-stats/generate_wiki_pages.py:307:0: C0301: Line too long (123/100) (line-too-long)
build-stats/generate_wiki_pages.py:308:0: C0301: Line too long (131/100) (line-too-long)
build-stats/generate_wiki_pages.py:315:0: C0301: Line too long (134/100) (line-too-long)
build-stats/generate_wiki_pages.py:320:0: C0301: Line too long (142/100) (line-too-long)
build-stats/generate_wiki_pages.py:322:0: C0301: Line too long (109/100) (line-too-long)
build-stats/generate_wiki_pages.py:326:0: C0301: Line too long (108/100) (line-too-long)
build-stats/generate_wiki_pages.py:330:0: C0301: Line too long (103/100) (line-too-long)
build-stats/generate_wiki_pages.py:353:0: C0301: Line too long (102/100) (line-too-long)
build-stats/generate_wiki_pages.py:353:0: W0311: Bad indentation. Found 20 spaces, expected 16 (bad-indentation)
build-stats/generate_wiki_pages.py:364:0: C0301: Line too long (169/100) (line-too-long)
build-stats/generate_wiki_pages.py:366:0: C0301: Line too long (106/100) (line-too-long)
build-stats/generate_wiki_pages.py:367:0: C0301: Line too long (105/100) (line-too-long)
build-stats/generate_wiki_pages.py:368:0: C0301: Line too long (101/100) (line-too-long)
build-stats/generate_wiki_pages.py:370:0: C0301: Line too long (106/100) (line-too-long)
build-stats/generate_wiki_pages.py:371:0: C0301: Line too long (105/100) (line-too-long)
build-stats/generate_wiki_pages.py:372:0: C0301: Line too long (101/100) (line-too-long)
build-stats/generate_wiki_pages.py:377:0: C0301: Line too long (113/100) (line-too-long)
build-stats/generate_wiki_pages.py:116:0: W1401: Anomalous backslash in string: '\|'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
build-stats/generate_wiki_pages.py:1:0: C0114: Missing module docstring (missing-module-docstring)
build-stats/generate_wiki_pages.py:1:0: E0401: Unable to import 'matplotlib.pyplot' (import-error)
build-stats/generate_wiki_pages.py:6:0: E0401: Unable to import 'pandas' (import-error)
build-stats/generate_wiki_pages.py:7:0: E0401: Unable to import 'numpy' (import-error)
build-stats/generate_wiki_pages.py:32:4: C0103: Variable name "AVG_MS_THRESHOLD" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_wiki_pages.py:111:0: C0116: Missing function or method docstring (missing-function-docstring)
build-stats/generate_wiki_pages.py:122:0: C0116: Missing function or method docstring (missing-function-docstring)
build-stats/generate_wiki_pages.py:124:4: W0621: Redefining name 'templates_total_times' from outer scope (line 377) (redefined-outer-name)
build-stats/generate_wiki_pages.py:125:4: W0621: Redefining name 'templates' from outer scope (line 377) (redefined-outer-name)
build-stats/generate_wiki_pages.py:128:4: W0621: Redefining name 'template_sets_times' from outer scope (line 377) (redefined-outer-name)
build-stats/generate_wiki_pages.py:129:4: W0621: Redefining name 'template_sets' from outer scope (line 377) (redefined-outer-name)
build-stats/generate_wiki_pages.py:132:4: W0621: Redefining name 'headers_times' from outer scope (line 377) (redefined-outer-name)
build-stats/generate_wiki_pages.py:133:4: W0621: Redefining name 'headers' from outer scope (line 377) (redefined-outer-name)
build-stats/generate_wiki_pages.py:135:37: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_wiki_pages.py:153:0: C0116: Missing function or method docstring (missing-function-docstring)
build-stats/generate_wiki_pages.py:153:25: W0621: Redefining name 'templates_total_times' from outer scope (line 377) (redefined-outer-name)
build-stats/generate_wiki_pages.py:155:4: C0103: Variable name "SMALL_SIZE" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_wiki_pages.py:156:4: C0103: Variable name "MEDIUM_SIZE" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_wiki_pages.py:157:4: C0103: Variable name "BIGGER_SIZE" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_wiki_pages.py:166:4: C0103: Variable name "barWidth" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_wiki_pages.py:167:9: C0103: Variable name "ax" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_wiki_pages.py:170:4: C0103: Variable name "TTT" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_wiki_pages.py:187:4: C0103: Variable name "yAxies" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_wiki_pages.py:195:4: C0103: Variable name "yTicks" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_wiki_pages.py:196:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
build-stats/generate_wiki_pages.py:155:4: W0612: Unused variable 'SMALL_SIZE' (unused-variable)
build-stats/generate_wiki_pages.py:167:4: W0612: Unused variable 'fig' (unused-variable)
build-stats/generate_wiki_pages.py:191:8: W0612: Unused variable 'idx' (unused-variable)
build-stats/generate_wiki_pages.py:204:0: C0116: Missing function or method docstring (missing-function-docstring)
build-stats/generate_wiki_pages.py:208:0: C0116: Missing function or method docstring (missing-function-docstring)
build-stats/generate_wiki_pages.py:211:4: W0621: Redefining name 'last_builds' from outer scope (line 382) (redefined-outer-name)
build-stats/generate_wiki_pages.py:209:4: C0103: Variable name "PREVIOUS_BUILDS_FILENAME" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_wiki_pages.py:210:4: C0103: Variable name "df" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_wiki_pages.py:244:0: C0116: Missing function or method docstring (missing-function-docstring)
build-stats/generate_wiki_pages.py:247:4: W0621: Redefining name 'last_builds' from outer scope (line 382) (redefined-outer-name)
build-stats/generate_wiki_pages.py:245:4: C0103: Variable name "PREVIOUS_BUILDS_FILENAME" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_wiki_pages.py:246:4: C0103: Variable name "df" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_wiki_pages.py:280:0: C0116: Missing function or method docstring (missing-function-docstring)
build-stats/generate_wiki_pages.py:284:0: C0116: Missing function or method docstring (missing-function-docstring)
build-stats/generate_wiki_pages.py:295:0: C0116: Missing function or method docstring (missing-function-docstring)
build-stats/generate_wiki_pages.py:295:19: W0621: Redefining name 'last_builds' from outer scope (line 382) (redefined-outer-name)
build-stats/generate_wiki_pages.py:301:4: C0103: Variable name "PAGE_NAME" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_wiki_pages.py:302:41: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_wiki_pages.py:303:8: C0103: Variable name "WIKI_PAGE" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_wiki_pages.py:336:0: C0116: Missing function or method docstring (missing-function-docstring)
build-stats/generate_wiki_pages.py:343:4: C0103: Variable name "PERF_TESTS_URL" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_wiki_pages.py:357:4: C0103: Variable name "PAGE_NAME" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_wiki_pages.py:358:41: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_wiki_pages.py:377:4: C0103: Constant name "templates" doesn't conform to UPPER_CASE naming style (invalid-name)
build-stats/generate_wiki_pages.py:377:15: C0103: Constant name "template_sets" doesn't conform to UPPER_CASE naming style (invalid-name)
build-stats/generate_wiki_pages.py:377:30: C0103: Constant name "headers" doesn't conform to UPPER_CASE naming style (invalid-name)
build-stats/generate_wiki_pages.py:377:39: C0103: Constant name "templates_total_times" doesn't conform to UPPER_CASE naming style (invalid-name)
build-stats/generate_wiki_pages.py:377:62: C0103: Constant name "template_sets_times" doesn't conform to UPPER_CASE naming style (invalid-name)
build-stats/generate_wiki_pages.py:377:83: C0103: Constant name "headers_times" doesn't conform to UPPER_CASE naming style (invalid-name)
build-stats/generate_wiki_pages.py:382:4: C0103: Constant name "last_builds" doesn't conform to UPPER_CASE naming style (invalid-name)
build-stats/generate_wiki_pages.py:4:0: W0611: Unused import requests (unused-import)
build-stats/generate_wiki_pages.py:5:0: W0611: Unused date imported from datetime (unused-import)
build-stats/generate_wiki_pages.py:7:0: W0611: Unused numpy imported as np (unused-import)
build-stats/generate_wiki_pages.py:2:0: C0411: standard import "import argparse" should be placed before "import matplotlib.pyplot as plt" (wrong-import-order)
build-stats/generate_wiki_pages.py:3:0: C0411: standard import "import os" should be placed before "import matplotlib.pyplot as plt" (wrong-import-order)
build-stats/generate_wiki_pages.py:4:0: C0411: third party import "import requests" should be placed before "import matplotlib.pyplot as plt" (wrong-import-order)
build-stats/generate_wiki_pages.py:5:0: C0411: standard import "from datetime import date" should be placed before "import requests" (wrong-import-order)
************* Module generate_build_graph
build-stats/generate_build_graph.py:59:0: C0330: Wrong continued indentation (remove 2 spaces).
            new_run_num, new_date, commit_id]],
          | ^ (bad-continuation)
build-stats/generate_build_graph.py:90:0: C0301: Line too long (109/100) (line-too-long)
build-stats/generate_build_graph.py:106:0: C0301: Line too long (118/100) (line-too-long)
build-stats/generate_build_graph.py:163:0: C0301: Line too long (109/100) (line-too-long)
build-stats/generate_build_graph.py:164:0: C0301: Line too long (114/100) (line-too-long)
build-stats/generate_build_graph.py:167:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
build-stats/generate_build_graph.py:1:0: C0114: Missing module docstring (missing-module-docstring)
build-stats/generate_build_graph.py:1:0: E0401: Unable to import 'matplotlib.pyplot' (import-error)
build-stats/generate_build_graph.py:6:0: E0401: Unable to import 'pandas' (import-error)
build-stats/generate_build_graph.py:65:4: W0621: Redefining name 'run_nums' from outer scope (line 178) (redefined-outer-name)
build-stats/generate_build_graph.py:66:4: W0621: Redefining name 'dates' from outer scope (line 178) (redefined-outer-name)
build-stats/generate_build_graph.py:29:0: R0914: Too many local variables (22/15) (too-many-locals)
build-stats/generate_build_graph.py:54:4: C0103: Variable name "PREVIOUS_BUILDS_FILENAME" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_build_graph.py:55:4: C0103: Variable name "df" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_build_graph.py:45:4: W0612: Unused variable 'run_number' (unused-variable)
build-stats/generate_build_graph.py:46:4: W0612: Unused variable 'built_int_head' (unused-variable)
build-stats/generate_build_graph.py:47:4: W0612: Unused variable 'built_int_base' (unused-variable)
build-stats/generate_build_graph.py:48:4: W0612: Unused variable 'built_int_ref' (unused-variable)
build-stats/generate_build_graph.py:74:4: W0612: Unused variable 'last_n_runs' (unused-variable)
build-stats/generate_build_graph.py:81:0: C0116: Missing function or method docstring (missing-function-docstring)
build-stats/generate_build_graph.py:82:8: C0103: Variable name "ax" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_build_graph.py:89:0: C0103: Argument name "ax" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_build_graph.py:111:0: C0103: Argument name "vt" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_build_graph.py:111:0: C0116: Missing function or method docstring (missing-function-docstring)
build-stats/generate_build_graph.py:111:19: W0621: Redefining name 'vt' from outer scope (line 178) (redefined-outer-name)
build-stats/generate_build_graph.py:111:23: W0621: Redefining name 'tests' from outer scope (line 178) (redefined-outer-name)
build-stats/generate_build_graph.py:111:30: W0621: Redefining name 'run_nums' from outer scope (line 178) (redefined-outer-name)
build-stats/generate_build_graph.py:111:40: W0621: Redefining name 'dates' from outer scope (line 178) (redefined-outer-name)
build-stats/generate_build_graph.py:111:0: R0914: Too many local variables (16/15) (too-many-locals)
build-stats/generate_build_graph.py:112:4: C0103: Variable name "SMALL_SIZE" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_build_graph.py:113:4: C0103: Variable name "MEDIUM_SIZE" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_build_graph.py:114:4: C0103: Variable name "BIGGER_SIZE" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_build_graph.py:123:4: C0103: Variable name "GRAPH_WIDTH" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_build_graph.py:124:4: C0103: Variable name "GRAPH_HEIGHT" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_build_graph.py:112:4: W0612: Unused variable 'SMALL_SIZE' (unused-variable)
build-stats/generate_build_graph.py:132:4: W0612: Unused variable 'fig' (unused-variable)
build-stats/generate_build_graph.py:155:0: C0103: Argument name "vt" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_build_graph.py:155:0: C0116: Missing function or method docstring (missing-function-docstring)
build-stats/generate_build_graph.py:155:19: W0621: Redefining name 'vt' from outer scope (line 178) (redefined-outer-name)
build-stats/generate_build_graph.py:155:23: W0621: Redefining name 'tests' from outer scope (line 178) (redefined-outer-name)
build-stats/generate_build_graph.py:158:4: C0103: Variable name "BUILD_TIME" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_build_graph.py:159:4: C0103: Variable name "BADGE_COLOR" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_build_graph.py:166:4: C0103: Variable name "BADGE_LOGO" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_build_graph.py:171:4: C0103: Variable name "r" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_build_graph.py:178:5: C0103: Constant name "vt" doesn't conform to UPPER_CASE naming style (invalid-name)
build-stats/generate_build_graph.py:178:9: C0103: Constant name "tests" doesn't conform to UPPER_CASE naming style (invalid-name)
build-stats/generate_build_graph.py:178:16: C0103: Constant name "run_nums" doesn't conform to UPPER_CASE naming style (invalid-name)
build-stats/generate_build_graph.py:178:26: C0103: Constant name "dates" doesn't conform to UPPER_CASE naming style (invalid-name)
build-stats/generate_build_graph.py:2:0: C0411: standard import "import argparse" should be placed before "import matplotlib.pyplot as plt" (wrong-import-order)
build-stats/generate_build_graph.py:3:0: C0411: standard import "import os" should be placed before "import matplotlib.pyplot as plt" (wrong-import-order)
build-stats/generate_build_graph.py:4:0: C0411: third party import "import requests" should be placed before "import matplotlib.pyplot as plt" (wrong-import-order)
build-stats/generate_build_graph.py:5:0: C0411: standard import "from datetime import date" should be placed before "import requests" (wrong-import-order)
************* Module generate_perf_graph
build-stats/generate_perf_graph.py:93:9: C0326: Exactly one space required after comma
    for k,v in per_test_dict.items():
         ^ (bad-whitespace)
build-stats/generate_perf_graph.py:106:86: C0326: No space allowed around keyword argument assignment
            ax1.bar(bar_positions[node], v[node]["mean"], label=f'node {node}', width = barWidth)
                                                                                      ^ (bad-whitespace)
build-stats/generate_perf_graph.py:1:0: C0114: Missing module docstring (missing-module-docstring)
build-stats/generate_perf_graph.py:1:0: E0401: Unable to import 'matplotlib.pyplot' (import-error)
build-stats/generate_perf_graph.py:5:0: E0401: Unable to import 'pandas' (import-error)
build-stats/generate_perf_graph.py:30:4: W0621: Redefining name 'memory_data' from outer scope (line 182) (redefined-outer-name)
build-stats/generate_perf_graph.py:31:4: W0621: Redefining name 'time_data' from outer scope (line 182) (redefined-outer-name)
build-stats/generate_perf_graph.py:42:4: W0621: Redefining name 'test_name' from outer scope (line 182) (redefined-outer-name)
build-stats/generate_perf_graph.py:12:0: R0914: Too many local variables (16/15) (too-many-locals)
build-stats/generate_perf_graph.py:64:0: C0116: Missing function or method docstring (missing-function-docstring)
build-stats/generate_perf_graph.py:65:4: C0103: Variable name "SMALL_SIZE" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_perf_graph.py:66:4: C0103: Variable name "MEDIUM_SIZE" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_perf_graph.py:67:4: C0103: Variable name "BIG_SIZE" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_perf_graph.py:77:0: C0116: Missing function or method docstring (missing-function-docstring)
build-stats/generate_perf_graph.py:77:24: W0621: Redefining name 'test_name' from outer scope (line 182) (redefined-outer-name)
build-stats/generate_perf_graph.py:77:35: W0621: Redefining name 'time_data' from outer scope (line 182) (redefined-outer-name)
build-stats/generate_perf_graph.py:77:0: R0914: Too many local variables (17/15) (too-many-locals)
build-stats/generate_perf_graph.py:85:17: R1718: Consider using a set comprehension (consider-using-set-comprehension)
build-stats/generate_perf_graph.py:88:8: R1704: Redefining argument with the local name 'test_name' (redefined-argument-from-local)
build-stats/generate_perf_graph.py:91:32: C0121: Comparison to True should be just 'expr' (singleton-comparison)
build-stats/generate_perf_graph.py:93:10: C0103: Variable name "v" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_perf_graph.py:97:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
build-stats/generate_perf_graph.py:98:8: C0103: Variable name "barWidth" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_perf_graph.py:82:4: W0612: Unused variable 'name_one' (unused-variable)
build-stats/generate_perf_graph.py:94:8: W0612: Unused variable 'fig' (unused-variable)
build-stats/generate_perf_graph.py:122:0: C0116: Missing function or method docstring (missing-function-docstring)
build-stats/generate_perf_graph.py:122:26: W0621: Redefining name 'test_name' from outer scope (line 182) (redefined-outer-name)
build-stats/generate_perf_graph.py:122:37: W0621: Redefining name 'memory_data' from outer scope (line 182) (redefined-outer-name)
build-stats/generate_perf_graph.py:130:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
build-stats/generate_perf_graph.py:123:4: W0612: Unused variable 'fig' (unused-variable)
build-stats/generate_perf_graph.py:146:0: C0116: Missing function or method docstring (missing-function-docstring)
build-stats/generate_perf_graph.py:146:28: W0621: Redefining name 'test_name' from outer scope (line 182) (redefined-outer-name)
build-stats/generate_perf_graph.py:158:4: C0103: Variable name "barWidth" doesn't conform to snake_case naming style (invalid-name)
build-stats/generate_perf_graph.py:147:4: W0612: Unused variable 'fig' (unused-variable)
build-stats/generate_perf_graph.py:182:4: C0103: Constant name "test_name" doesn't conform to UPPER_CASE naming style (invalid-name)
build-stats/generate_perf_graph.py:182:15: C0103: Constant name "time_data" doesn't conform to UPPER_CASE naming style (invalid-name)
build-stats/generate_perf_graph.py:182:26: C0103: Constant name "memory_data" doesn't conform to UPPER_CASE naming style (invalid-name)
build-stats/generate_perf_graph.py:2:0: C0411: standard import "import argparse" should be placed before "import matplotlib.pyplot as plt" (wrong-import-order)
build-stats/generate_perf_graph.py:3:0: C0411: standard import "import os" should be placed before "import matplotlib.pyplot as plt" (wrong-import-order)
build-stats/generate_perf_graph.py:4:0: C0411: standard import "from datetime import date" should be placed before "import matplotlib.pyplot as plt" (wrong-import-order)
build-stats/generate_perf_graph.py:6:0: C0411: standard import "from collections import defaultdict" should be placed before "import matplotlib.pyplot as plt" (wrong-import-order)
build-stats/generate_perf_graph.py:1:0: R0801: Similar lines in 2 files
==generate_build_graph:111
==generate_wiki_pages:154
    SMALL_SIZE = 15
    MEDIUM_SIZE = 25
    BIGGER_SIZE = 35

    plt.rc('font', size=MEDIUM_SIZE, family='serif')
    plt.rc('axes', titlesize=MEDIUM_SIZE, labelsize=MEDIUM_SIZE)
    plt.rc('xtick', labelsize=MEDIUM_SIZE) (duplicate-code)
build-stats/generate_perf_graph.py:1:0: R0801: Similar lines in 2 files
==generate_build_graph:0
==generate_wiki_pages:0
import matplotlib.pyplot as plt
import argparse
import os
import requests
from datetime import date
import pandas as pd (duplicate-code)

-----------------------------------
Your code has been rated at 4.88/10
```

</details>

**Review by lifflander — APPROVED** [review]
Looks great!

**Review by cz4rs — APPROVED** [review]
looks good to me!

**Pull request merged**
